# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22c93fc694458e4e40d8ca28c1578c3bea4ef662aac61f7deb6cb287eb9853cc851342167d3c5d5c95e2e1249be947ea222fdeff0bd389e8d6bd8aac365222f2

test:
  secret_key_base: 8279e5efc82177ea161745834cdf3c72479a6943576e170013b5d92610eb58d3218963ec221ad81609b1bd10e1aec5ffdf1934a120eaded28f2c4c6f4ce0fd55

# Do not keep production secrets in the repository,
# instead read values from the CZ::Vault.
# Because we need to allow this ERB interpolation to succeed without raising
# an error, we default to `nil`, here, which won't provide something usable in
# the event the data's missing from the production vault, but is just fine for
# ensuring the template can render without raising.
production:
  secret_key_base: <%= Vault[:secret_key_base, default: nil] %>
